### PR TITLE
Add inclusions option.

### PR DESCRIPTION
**Pull request by yavorsky**
Sometimes, we need to consider dates, that **overrides weekends and exclusions**. For example, one-off work days: user want to work on sunday, even if this day isn't included in weekdays, or person is crazy and want christmas as a work day, but usually it is holiday for him and exist in exclusions.

We should use something like:

``` javascript
moment().weekdayCalc({  
  rangeStart: '1 Apr 2016',  
  rangeEnd: '31 Mar 2017',  
  weekdays: [1,2,3,4,5],
  exclusions: ['6 Apr 2016','7 Apr 2016']
  inclusions: ['10 Apr 2016']
})
```

### CODE REVIEW

**Comment by andruhon** [comment]
Looks good. Could you please do a rebase on to eba9c21?

**Comment by andruhon** [comment]
Artem, please let me know if you have any difficulties with merging/rebasing this one.

**Comment by yavorsky** [comment]
@andruhon No, just fell asleep)

**Comment by andruhon** [comment]
Cool! Thank you for contribution! I would also appreciate tests for inclusions.

**Pull request merged**
